---
steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -t, "nesachirou/erlang:21", priv/erl21]
    id: build-erl21
    waitFor: ["-"]
    timeout: 1200s
  - name: gcr.io/gcp-runtimes/container-structure-test
    args: [test, --image, "nesachirou/erlang:21", --config, priv/erl21/container-structure-test.yml]
    id: test-erl21
    waitFor: [build-erl21]

  - name: gcr.io/cloud-builders/docker
    args: [build, -t, "nesachirou/erlang:22", -t, "nesachirou/erlang:latest", priv/erl22]
    id: build-erl22
    waitFor: ["-"]
    timeout: 1200s
  - name: gcr.io/gcp-runtimes/container-structure-test
    args: [test, --image, "nesachirou/erlang:22", --config, priv/erl22/container-structure-test.yml]
    id: test-erl22
    waitFor: [build-erl22]

  - name: gcr.io/cloud-builders/docker
    args: [build, -t, "nesachirou/elixir:1.8_erl21", priv/ex1.8_erl21]
    id: build-ex1.8_erl21
    waitFor: [test-erl21]
    timeout: 600s
  - name: gcr.io/gcp-runtimes/container-structure-test
    args: [test, --image, "nesachirou/elixir:1.8_erl21", --config, priv/ex1.8_erl21/container-structure-test.yml]
    id: test-ex1.8_erl21
    waitFor: [build-ex1.8_erl21]

  - name: gcr.io/cloud-builders/docker
    args: [build, -t, "nesachirou/elixir:1.8_erl22", priv/ex1.8_erl22]
    id: build-ex1.8_erl22
    waitFor: [test-erl22]
    timeout: 600s
  - name: gcr.io/gcp-runtimes/container-structure-test
    args: [test, --image, "nesachirou/elixir:1.8_erl22", --config, priv/ex1.8_erl22/container-structure-test.yml]
    id: test-ex1.8_erl22
    waitFor: [build-ex1.8_erl22]

  - name: gcr.io/cloud-builders/docker
    args: [build, -t, "nesachirou/elixir:1.9_erl21", priv/ex1.9_erl21]
    id: build-ex1.9_erl21
    waitFor: [test-erl21]
    timeout: 600s
  - name: gcr.io/gcp-runtimes/container-structure-test
    args: [test, --image, "nesachirou/elixir:1.9_erl21", --config, priv/ex1.9_erl21/container-structure-test.yml]
    id: test-ex1.9_erl21
    waitFor: [build-ex1.9_erl21]

  - name: gcr.io/cloud-builders/docker
    args: [build, -t, "nesachirou/elixir:1.9_erl22", -t, "nesachirou/elixir:latest", priv/ex1.9_erl22]
    id: build-ex1.9_erl22
    waitFor: [test-erl22]
    timeout: 600s
  - name: gcr.io/gcp-runtimes/container-structure-test
    args: [test, --image, "nesachirou/elixir:1.9_erl22", --config, priv/ex1.9_erl22/container-structure-test.yml]
    id: test-ex1.9_erl22
    waitFor: [build-ex1.9_erl22]

  - name: gcr.io/cloud-builders/docker
    args: [login, -u, nesachirou, -p, $_DOCKER_REGISTRY_PASSWORD]

timeout: 1800s
images:
  - "nesachirou/erlang:21"
  - "nesachirou/erlang:22"
  - "nesachirou/erlang:latest"
  - "nesachirou/elixir:1.8_erl21"
  - "nesachirou/elixir:1.8_erl22"
  - "nesachirou/elixir:1.9_erl21"
  - "nesachirou/elixir:1.9_erl22"
  - "nesachirou/elixir:latest"
options:
  machineType: N1_HIGHCPU_8
